baseURL = "/"
languageCode = "en-us"
title = "才智教练与情商发展中心 / Cheers Coaching and EQ Evolution Center"
themesDir = "themes"
theme = "cheerseq"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo.png"
    mobile_height = "36px"
    desktop = "images/logo/logo.png"
    desktop_height = "36px"
    alt = "才智教练与情商发展中心 / Cheers Coaching and EQ Evolution Center"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '才智教练与情商发展中心 / Cheers Coaching and EQ Evolution Center'

[menu]
  # Main Menu

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true